#!/bin/bash

cat <<EOF > messenger.nomad
job "messenger" {
  datacenters = ["dc1"]

  type = "batch"
  parameterized {
      meta_required = ["author", "message"]
  }

  group "messenger" {
    count = 1

    task "send" {
      driver = "exec"
      config {
        command = "echo"
        args = ["\${NOMAD_META_AUTHOR} says \${NOMAD_META_MESSAGE}"]
      }

      resources {
        cpu    = 100
        memory = 32
        network {
          mbits = 1
        }
      }
    }
  }
}
EOF

nomad run messenger.nomad
rm messenger.nomad

exit 0
