#!/bin/bash

# Check if there is a job called example
JOB_ID=$(curl -s localhost:4646/v1/job/example | jq -r .ID)
if [ "$JOB_ID" != "example" ]; then
  fail-message "There is no job with id example"
  exit 1
fi

# Check if it is currently running
JOB_STATUS=$(curl -s localhost:4646/v1/job/example | jq -r .Status)
if [ "$JOB_STATUS" != "running" ]; then
  fail-message "The example job is not currently running"
  exit 1
fi

exit 0
