#!/bin/bash

# Check if there is a job with desired canaries = 1
DESIRED_CANARIES=$(curl -s localhost:4646/v1/deployments | jq '.[] | select(.TaskGroups.website.DesiredCanaries == 1)')
if [ -z "$DESIRED_CANARIES" ]; then
  fail-message "There is no example job that has canary set to 1"
  exit 1
fi

# Check if the canary was promoted
PROMOTED_CANARIES=$(echo "$DESIRED_CANARIES"| jq '.TaskGroups | select (.website.Promoted) | length > 0')
if [ "$PROMOTED_CANARIES" != "true" ]; then
  fail-message "The canary release was not promoted"
  exit 1
fi

exit 0
