#!/bin/bash
cat <<EOF > example.nomad
job "example" {
  datacenters = ["dc1"]
  type = "service"

  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    auto_revert = false
    canary = 1
  }

  group "website" {
    count = 1

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:1.14-alpine"
        port_map {
          http = 80
        }
      }

      resources {
        cpu    = 500
        memory = 256
        network {
          mbits = 10
          port "http" {}
        }
      }
    }
  }
}
EOF

nomad run example.nomad